- name: Configure device
  hosts: localhost
  connection: local
  gather_facts: no
 
  tasks:
  - name: NSO global variables
    include_vars:
      file: nso.yaml
      name: nso

  - name: Device configuration
    nso_config:
      url: "{{ nso.url }}"
      username: "{{ nso.username }}"
      password: "{{ nso.password }}"
      data:
        tailf-ncs:devices:
          device:
          - name: "{{ device }}"

